# Generated by Django 5.2.4 on 2025-08-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(blank=True, help_text='Name of the college/university', max_length=200, null=True),
        ),
    ]
