# Generated by Django 5.2.4 on 2025-08-13 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message_deleted_message_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_conversation_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
